### ISSUE TITLE
Bug Report: Bopeebo desync? Needs further analysis.

### ISSUE THREAD

**Issue by ScrubRTA** [KadeArchive/Kade-Engine#1197]
So I tried to MFC Bopeebo with a blank, invisible note skin (don't ask), and I'm consistently getting 50-70ms errors on specific verses where I feel like there should be none - for example, I can get the first verse pretty consistent but then almost always miss a Sick note on the 2nd verse. I'm beginning to believe this isn't my fault - the vocals might not be entirely on beat. I've memorized the placements of every note with ease, but not having judgment lines and simply using audio cues has helped me realize the possibility of something other than me being wrong. This may be present to some extent in other songs, but Bopeebo is the only song simple enough for me to get consistent at with blind notes.

**Comment by KlutchDj** [comment]
this is pretty much of a input bug. you cant really MFC it as if right now on 1.5.4. because when holding a slider and a note is literally right under it , when releasing the input , the game thinks your inputting the note below that slider. nothing is wrong with the charting. but thats just my assumption anyway , so i could be wrong

**Comment by Kade-github** [comment]
yeah this was already fixed in the latest commit on master.

**Comment by ScrubRTA** [comment]
I wasn't talking about 1.5.4, actually, I was using 1.5.2 where the input works. I assume 1.5.4 uses the same chart?

**Comment by KlutchDj** [comment]
yes , we recommend that you play on the more recent versions because kade isnt going to fix a bug that was on 1.5.2 unless it is still present in future updates.

**Comment by ScrubRTA** [comment]
You know what, never mind. It's not the chart, it's just me. I'm not good enough to play with blind notes.
