### ISSUE TITLE
"No difficulties found for chart, skipping" popup appears on Kade 1.7.1 Pre-Release in Debug Build, Clicking OK closes the game

### ISSUE THREAD

**Issue by swordcube** [KadeArchive/Kade-Engine#2246]
I am trying to compile Kade Engine 1.6.2 on Arch Linux 64-bit and when i do "lime build linux"
This pops up seconds later:

**source/PlayState.hx:73: characters 8-15 : Module Discord does not define type Discord
source/PlayState.hx:2113: characters 4-17 : Type not found : DiscordClient
source/PlayState.hx:2185: characters 3-16 : Type not found : DiscordClient
source/PlayState.hx:2149: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:2167: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:2433: characters 4-17 : Type not found : DiscordClient
source/PlayState.hx:2858: characters 5-18 : Type not found : DiscordClient
source/PlayState.hx:2894: characters 5-18 : Type not found : DiscordClient**

I've never really touched HaxeFlixel before so i don't really know what to do here

**This used to be an issue about KE 1.6.2 not compiling, but look at the comments.**

**Comment by EliteMasterEric** [comment]
This is probably fixed in Kade Engine version 1.7, check the stable branch.

**Comment by swordcube** [comment]
> This is probably fixed in Kade Engine version 1.7, check the stable branch.

upgrading to kade 1.7 on the stable branch...uh no luck, it doesn't even compile, it just spits out a bunch of lua errors and then just stops randomly, i'm on the prerelease version and it compiles perfectly fine {atleast on the debug build} and now i have a whole different issue. i can't go into freeplay because of this:
![death](https://user-images.githubusercontent.com/49110074/133361371-8e301733-70cf-4722-bc3e-bf35b4e940cb.png)
when i click "OK" the game just closes. what do i do

**Comment by swordcube** [comment]
Update: I know what song's fucking up, It's the tutorial, All of it's jsons are there, But the game thinks otherwise.
Still don't have a fix.

**Comment by EliteMasterEric** [comment]
> it doesn't even compile, it just spits out a bunch of lua errors and then just stops randomly

For this issue, the problem was that the 1.7 rework of modcharts does not work on Windows. There are macros in the code to disable them on Linux, but with the rework they weren't all put in the proper spots.

I have both fixed these problems and performed some fixes to Github's continuous integration such that any potential PRs will display an :x: if they do not work properly on Linux.

> Update: I know what song's fucking up, It's the tutorial, All of it's jsons are there, But the game thinks otherwise.

I'll try to take a look.

**Comment by swordcube** [comment]
Thank you. Where do i get the fixed 1.7? Is it the Pre-Release version?

**Comment by swordcube** [comment]
I probably should have provided what happens when i compile regular stable 1.7 earlier but here you go:
![hell](https://user-images.githubusercontent.com/49110074/133508129-a014c50a-67d7-408c-a8db-58cac1cfdb46.png)
![hell has ended](https://user-images.githubusercontent.com/49110074/133508139-113038cf-06ce-4548-a8f8-c363d34453e4.png)

This happens after Link:ApplicationMain-debug, And it never creates the executable for the game because it just..stops

**Comment by EliteMasterEric** [comment]
Hmmm, I remember seeing that error before but not how I fixed it.

Could you try running this to reinstall LuaJIT?

```
haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git linc_luajit https://github.com/MasterEric/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
```

**Comment by swordcube** [comment]
> Hmmm, I remember seeing that error before but not how I fixed it.
> 
> Could you try running this to reinstall LuaJIT?
> 
> ```
> haxelib remove linc_luajit
> haxelib remove hxvm-luajit
> haxelib git linc_luajit https://github.com/MasterEric/linc_luajit.git
> haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
> ```

i don't know if this is the problem, but i could try.

**Comment by swordcube** [comment]
so in 1.7.1-PreRelease kade engine, you know how i had that "No difficulties found for chart, skipping" thing? I think i know why it's happening. It's trying to load the chart with the capital letters in the name
Example:
In freeplaySongList.txt, tutorial is formatted as "Tutorial", I think it's trying to load "Tutorial" instead of "tutorial", so i made a sloppy workaround which is just a bunch of this:

case "Song": "song"

or something like that, it works but if there's any other fix please let me know.

**Comment by swordcube** [comment]
i finally found a good fix, in FreeplayState.hx when it tries to load the song i made it convert the song to lowercase so it loads that version instead. i'm happily using kade engine 1.7.1-prerelease now.

**Comment by EliteMasterEric** [comment]
One of my PRs (the second ModCore one) goes all the way with fixing this; it defines a song ID and a song name. The song ID is the (fully-lowercase) name of the folder and the song name is either the same as the ID or specified in a metadata file. This not only fixes the issue above but also gets rid of that dumb case structure that had Dad Battle, Philly Nice, and M.I.L.F that got copy-pasted in 20 different locations (all three of those names are defined in the `assets/data/<songname>/_meta.json` file now.)

**Comment by swordcube** [comment]
> One of my PRs (the second ModCore one) goes all the way with fixing this; it defines a song ID and a song name. The song ID is the (fully-lowercase) name of the folder and the song name is either the same as the ID or specified in a metadata file. This not only fixes the issue above but also gets rid of that dumb case structure that had Dad Battle, Philly Nice, and M.I.L.F that got copy-pasted in 20 different locations (all three of those names are defined in the `assets/data/<songname>/_meta.json` file now.)

how do i get this fix then? do i just clone the master branch again? {this is how i got the prerelease version}
