### ISSUE TITLE
game cannot find asset/data/philly nice/phillr nice-hard.json

### ISSUE THREAD

**Issue by realepicgamer** [KadeArchive/Kade-Engine#779]
bruh what is this
![image](https://user-images.githubusercontent.com/81527403/121070650-a54b3e80-c7d7-11eb-8cb0-dfbf7144ccfe.png)

**Comment by isakube** [comment]
this is fixed in the stable branch, update your source

**Comment by Lucky-56** [comment]
same bug: #778
this is fixed in the master branch

**Comment by JOELwindows7** [comment]
also #778 
Yes. Coders, you forgot to convert the path from space to `-` in the PlayState.hx

the line [2518](https://github.com/KadeDev/Kade-Engine/blob/stable/source/PlayState.hx#L2518 )

in `function endSong()` when going to load next song.

you have  
`PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + difficulty, PlayState.storyPlaylist[0]);`  
while that should've been
`PlayState.SONG = Song.loadFromJson(StringTools.replace(PlayState.storyPlaylist[0]," ", "-").toLowerCase() + difficulty, StringTools.replace(PlayState.storyPlaylist[0]," ", "-").toLowerCase());` just like with the FreePlay state or Story menu.

Pls pull that fixed from master to here, stable yay.

**Comment by Lucky-56** [comment]
**fixed in master**

how to fix if you know how to compile:
1. download [master-branch](https://github.com/KadeDev/Kade-Engine/tree/master) source code
2. compile using the steps of [their website](https://kadedev.github.io/Kade-Engine/building) (assuming you're on windows `lime build windows -final`)
3. then head into `export/final/bin` and there you have your self compiled `Kade Engine.exe`

**Comment by Lucky-56** [comment]
fixed in Kade Engine v1.5.2
reminder to close this issue

**Comment by JOELwindows7** [comment]
> fixed in Kade Engine v1.5.2
> reminder to close this issue

# Yay
Finally. thancc

**Comment by Lucky-56** [comment]
@daniel11420 I'm very _very_ sorry for that @ but... you missed one...\
\
\
\
don't cry... please
I'm worried

**Comment by puyoxyz** [comment]
> @daniel11420 I'm very _very_ sorry for that @ but... you missed one...
> 
> 
> 
> don't cry... please
> I'm worried

fgjdrolighjdgkljhgjdlkgjseld don't apologize for @ ing me!! its ok!! dont think of me as some god im just your average programmer with thigh highs!!! you can @ me!!! :3

**Comment by Lucky-56** [comment]
well in hindsight you still are mighty on this repo (fork)
